menu:
  configurations: 配置
  five-minutes-setup: 开始使用
  theme-settings: 主题设定
  third-party-services: 第三方服务
  schemes: Schemes
  faqs: 常见问题
  language: 语言
  english: 英文
  chinese: 简体中文
  about: 关于
  preview-mist: 在线预览
  github-repo: GitHub 仓库地址
